### ISSUE TITLE
v0.1.0 を公開してみる

### ISSUE THREAD

**Issue by mashabow** [mashabow/issue-duplicator-action#17]
#15 で仕込んだリリースまわりの処理がうまく動くか、試しに v0.1.0 を公開してみる。

リポジトリのページ上からリリースの内容を準備。

<img src="https://user-images.githubusercontent.com/6268183/204143013-7aadb76f-0647-416c-b86a-f70cf31b2d66.png">

[Publish release] をクリックすると実際にリリースが作成され、Marketplace に公開された 👏

https://github.com/marketplace/actions/issue-duplicator

<img width="1130" alt="Issue_Duplicator_·_Actions_·_GitHub_Marketplace" src="https://user-images.githubusercontent.com/6268183/204143255-10ef190e-20e9-4f5d-8c77-307f7cb08386.png">

**Comment by mashabow** [comment]
リリース作成時には `main` ブランチ上のコミット [`5500d4b`](https://github.com/mashabow/issue-duplicator-action/commit/5500d4bf0dcd399204f132983d7302f90fd2d7af) を v0.1.0 としたが、#15 で仕込んだ https://github.com/JasonEtco/build-and-tag-action によって、ビルドされたものに自動的に置き換わる。

https://github.com/mashabow/issue-duplicator-action/releases/tag/v0.1.0

<img width="1130" alt="Release_v0_1_0_·_mashabow_issue-duplicator-action" src="https://user-images.githubusercontent.com/6268183/204143352-a7e20e46-0e52-4338-8052-30655bfa7f81.png">

置き換わった後のコミットは、`action.yml` と `dist/index.js` だけになっている。このコミットは、ブランチには属していない。

https://github.com/mashabow/issue-duplicator-action/tree/v0.1.0

<img width="1130" alt="mashabow_issue-duplicator-action_at_v0_1_0" src="https://user-images.githubusercontent.com/6268183/204143551-f0830fed-0528-46de-bf54-4689b1618588.png">

また同時に、`vx.y.z`, `vx.y`, `vx` の 3 つのタグがこのコミットを指すように付与されている。

https://github.com/mashabow/issue-duplicator-action/tags

<img width="1130" alt="Tags_·_mashabow_issue-duplicator-action" src="https://user-images.githubusercontent.com/6268183/204143690-53991857-69a5-4308-971f-b06363545d68.png">

**Comment by mashabow** [comment]
別リポジトリに以下の workflow を用意して実行したら、

```yml
name: Issue Duplicator

on:
  issue_comment:
    types: [created]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: mashabow/issue-duplicator-action@v0.1.0
        with:
          github-token: ${{ secrets.REPO_PROJECT_PAT }}
```

ソースマップ絡みでエラーになった 😇

<img width="1044" alt="動作確認用_·_mashabow_issue-duplicator-action-test_639083d" src="https://user-images.githubusercontent.com/6268183/204143893-f36b59fe-ff6b-4234-858e-a21334fe50e1.png">
